// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "MainMenuUIAbstract.h"

inline void MainMenuUIAbstract::cb_motorcycleBtn_i(fltk::Button* o, const char* v) {
  cb_start(o,v)
;}
void MainMenuUIAbstract::cb_motorcycleBtn(fltk::Button* o, const char* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->parent()->user_data()))->cb_motorcycleBtn_i(o,v);
}

inline void MainMenuUIAbstract::cb_carBtn_i(fltk::Button* o, const char* v) {
  cb_start(o,v)
;}
void MainMenuUIAbstract::cb_carBtn(fltk::Button* o, const char* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->parent()->user_data()))->cb_carBtn_i(o,v);
}

inline void MainMenuUIAbstract::cb_truckBtn_i(fltk::Button* o, const char* v) {
  cb_start(o,v)
;}
void MainMenuUIAbstract::cb_truckBtn(fltk::Button* o, const char* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->parent()->user_data()))->cb_truckBtn_i(o,v);
}

inline void MainMenuUIAbstract::cb_busBtn_i(fltk::Button* o, const char* v) {
  cb_start(o,v)
;}
void MainMenuUIAbstract::cb_busBtn(fltk::Button* o, const char* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->parent()->user_data()))->cb_busBtn_i(o,v);
}

inline void MainMenuUIAbstract::cb_exitBtn_i(fltk::Button*, void*) {
  cb_exit()
;}
void MainMenuUIAbstract::cb_exitBtn(fltk::Button* o, void* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->user_data()))->cb_exitBtn_i(o,v);
}

inline void MainMenuUIAbstract::cb_helpBtn_i(fltk::Button*, void*) {
  cb_help()
;}
void MainMenuUIAbstract::cb_helpBtn(fltk::Button* o, void* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->user_data()))->cb_helpBtn_i(o,v);
}

inline void MainMenuUIAbstract::cb_languagePUM_i(fltk::PopupMenu* o, void* v) {
  cb_selectLanguage(o,v)
;}
void MainMenuUIAbstract::cb_languagePUM(fltk::PopupMenu* o, void* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->user_data()))->cb_languagePUM_i(o,v);
}

inline void MainMenuUIAbstract::cb_fullscreenBtn_i(fltk::Button*, void*) {
  cb_fullscreen()
;}
void MainMenuUIAbstract::cb_fullscreenBtn(fltk::Button* o, void* v) {
  ((MainMenuUIAbstract*)(o->parent()->parent()->user_data()))->cb_fullscreenBtn_i(o,v);
}

MainMenuUIAbstract::MainMenuUIAbstract(int x, int y, int width, int height, const char* label): fltk::Window(x,y,width,height,label,true) {
  fltk::Group* w;
  
  {
fltk::Group* o = mainContainer = new fltk::Group(0, 0, 640, 480);
    w = o;
    o->shortcut(0xff1b);
    o->user_data((void*)(this));
    o->begin();
    
    {
fltk::Widget* o = new fltk::Widget(12, 6, 615, 100, _("Application Title") );
      o->box(fltk::HIGHLIGHT_UP_BOX);
      o->labeltype(fltk::EMBOSSED_LABEL);
    }
    
    {
fltk::Group* o = new fltk::Group(12, 123, 615, 210);
      o->box(fltk::ENGRAVED_BOX);
      o->begin();
      
      {
fltk::Group* o = new fltk::Group(16, 41, 580, 149, _("Select a Test Category") );
        o->labeltype(fltk::ENGRAVED_LABEL);
        o->begin();
        
        {
fltk::Button* o = motorcycleBtn = new fltk::Button(0, 20, 110, 110, _("Motorcycle") );
          o->callback((fltk::Callback*)cb_motorcycleBtn, (void*)("motorcycle"));
        }
        
        {
fltk::Button* o = carBtn = new fltk::Button(156, 20, 110, 110, _("Car") );
          o->callback((fltk::Callback*)cb_carBtn, (void*)("car"));
        }
        
        {
fltk::Button* o = truckBtn = new fltk::Button(313, 20, 110, 110, _("Truck") );
          o->callback((fltk::Callback*)cb_truckBtn, (void*)("truck"));
        }
        
        {
fltk::Button* o = busBtn = new fltk::Button(470, 20, 110, 110, _("Bus") );
          o->callback((fltk::Callback*)cb_busBtn, (void*)("bus"));
        }
        o->end();
        fltk::Group::current()->resizable(o);
      }
      o->end();
    }
    
    {
fltk::Group* o = new fltk::Group(12, 340, 615, 113);
      o->box(fltk::ENGRAVED_BOX);
      o->begin();
      
      {
fltk::Button* o = exitBtn = new fltk::Button(18, 18, 75, 75, _("Exit") );
        o->callback((fltk::Callback*)cb_exitBtn);
      }
      
      {
fltk::Button* o = helpBtn = new fltk::Button(521, 18, 75, 75, _("Help") );
        o->callback((fltk::Callback*)cb_helpBtn);
      }
      
      {
fltk::PopupMenu* o = languagePUM = new fltk::PopupMenu(230, 13, 178, 41, _("Select Language") );
        o->callback((fltk::Callback*)cb_languagePUM);
        o->begin();
        
        {
fltk::Item* o = new fltk::Item(_("Greek") );
          o->user_data((void*)("greek"));
        }
        
        {
fltk::Item* o = new fltk::Item(_("English") );
          o->user_data((void*)("english"));
        }
        
        {
fltk::Item* o = new fltk::Item(_("Russian") );
          o->user_data((void*)("russian"));
        }
        
        {
fltk::Item* o = new fltk::Item(_("Albanian") );
          o->user_data((void*)("albanian"));
        }
        o->end();
      }
      
      {
fltk::Button* o = fullscreenBtn = new fltk::Button(228, 59, 180, 41, _("Fullscreen") );
        o->type(fltk::Button::TOGGLE);
        o->callback((fltk::Callback*)cb_fullscreenBtn);
      }
      o->end();
    }
    new fltk::StatusBarGroup(0, 460, 640, 20, "This is the status bar");
    o->end();
    o->resizable(o);
  }
}

void MainMenuUIAbstract::cb_exit() {
}

void MainMenuUIAbstract::cb_help() {
}

void MainMenuUIAbstract::cb_fullscreen() {
}

void MainMenuUIAbstract::cb_start(fltk::Widget* pBtn, const char* tCategory) {
}

void MainMenuUIAbstract::cb_selectLanguage(fltk::Widget* sItem, void* userdata) {
}
