// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "QuestionViewUI.h"
#include <fltk/ask.h>
#include <stdlib.h>

inline void QuestionViewUI::cb_answerRB_i(fltk::RadioButton*, void*) {
  if (selectedRB() > -1) validateBtn->activate();
  else validateBtn->deactivate();
}
void QuestionViewUI::cb_answerRB(fltk::RadioButton* o, void* v) {
  ((QuestionViewUI*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_answerRB_i(o,v);
}

inline void QuestionViewUI::cb_exitBtn_i(fltk::Button*, void*) {
  if (fltk::ask("Do you want to quit?")) exit(0);
}
void QuestionViewUI::cb_exitBtn(fltk::Button* o, void* v) {
  ((QuestionViewUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_exitBtn_i(o,v);
}

inline void QuestionViewUI::cb_fullscreenBtn_i(fltk::Button*, void*) {
  if (this->fullscreen_flag) 
  {
      mainWindow->fullscreen_off( win_x, win_y,800,600);
      mainWindow->set_non_modal();
  }
  else 
  {
      win_x = mainWindow->x();
      win_y = mainWindow->y();
      mainWindow->fullscreen();
      mainWindow->set_modal();
      
  }
    
  if (fullscreen_flag) fullscreen_flag=false;
  else fullscreen_flag=true;
}
void QuestionViewUI::cb_fullscreenBtn(fltk::Button* o, void* v) {
  ((QuestionViewUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_fullscreenBtn_i(o,v);
}

inline void QuestionViewUI::cb_validateBtn_i(fltk::Button*, void*) {
  fltk::message("RadioButton selected: %d",selectedRB());
}
void QuestionViewUI::cb_validateBtn(fltk::Button* o, void* v) {
  ((QuestionViewUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_validateBtn_i(o,v);
}

QuestionViewUI::QuestionViewUI() {
  fltk::Window* w;
  
  {
fltk::Window* o = mainWindow = new fltk::Window(800, 600);
    w = o;
    o->shortcut(0xff1b);
    o->user_data((void*)(this));
    o->begin();
    
    {
fltk::Group* o = new fltk::Group(0, 0, 800, 600);
      o->begin();
      
      {
fltk::Group* o = LeftGroup = new fltk::Group(5, 5, 450, 590);
        o->set_vertical();
        o->box(fltk::THIN_DOWN_BOX);
        o->begin();
        
        {
fltk::Group* o = QuestionGroup = new fltk::Group(5, 5, 440, 465);
          o->set_vertical();
          o->box(fltk::THIN_UP_BOX);
          o->begin();
          
          {
fltk::TextDisplay* o = questionDisplay = new fltk::TextDisplay(5, 20, 430, 130, "Question #/#");
            o->labeltype(fltk::ENGRAVED_LABEL);
            o->labelsize(18);
            o->textsize(16);
            o->align(fltk::ALIGN_TOP);
            o->wrap_mode(true);
          }
          
          {
fltk::Group* o = AnswerGroup = new fltk::Group(5, 155, 430, 305);
            o->box(fltk::THIN_DOWN_BOX);
            o->begin();
            
            {
fltk::RadioButton* o = answerRB[0] = new fltk::RadioButton(5, 1, 420, 75, "Answer 0");
              o->buttonbox(fltk::BORDER_BOX);
              o->labelsize(16);
              o->textsize(16);
              o->callback((fltk::Callback*)cb_answerRB);
              o->align(fltk::ALIGN_LEFT|fltk::ALIGN_INSIDE|fltk::ALIGN_WRAP);
            }
            
            {
fltk::RadioButton* o = answerRB[1] = new fltk::RadioButton(5, 77, 420, 75, "Answer 1");
              o->buttonbox(fltk::BORDER_BOX);
              o->labelsize(16);
              o->textsize(16);
              o->callback((fltk::Callback*)cb_answerRB);
              o->align(fltk::ALIGN_LEFT|fltk::ALIGN_INSIDE|fltk::ALIGN_WRAP);
            }
            
            {
fltk::RadioButton* o = answerRB[2] = new fltk::RadioButton(5, 153, 420, 75, "Answer 2");
              o->buttonbox(fltk::BORDER_BOX);
              o->labelsize(16);
              o->textsize(16);
              o->callback((fltk::Callback*)cb_answerRB);
              o->align(fltk::ALIGN_LEFT|fltk::ALIGN_INSIDE|fltk::ALIGN_WRAP);
            }
            
            {
fltk::RadioButton* o = answerRB[3] = new fltk::RadioButton(5, 229, 420, 75, "Answer 3");
              o->buttonbox(fltk::BORDER_BOX);
              o->labelsize(16);
              o->textsize(16);
              o->callback((fltk::Callback*)cb_answerRB);
              o->align(fltk::ALIGN_LEFT|fltk::ALIGN_INSIDE|fltk::ALIGN_WRAP);
            }
            o->end();
          }
          o->end();
        }
        
        {
fltk::Group* o = MainControlsGroup = new fltk::Group(5, 475, 440, 110);
          o->box(fltk::THIN_UP_BOX);
          o->begin();
          
          {
fltk::Button* o = exitBtn = new fltk::Button(10, 15, 115, 80, "Exit");
            o->labelfont(fltk::HELVETICA_BOLD);
            o->callback((fltk::Callback*)cb_exitBtn);
          }
          
          {
fltk::Button* o = fullscreenBtn = new fltk::Button(165, 15, 115, 80, "Fullscreen");
            o->labelfont(fltk::HELVETICA_BOLD);
            o->labelsize(14);
            o->callback((fltk::Callback*)cb_fullscreenBtn);
          }
          
          {
fltk::Button* o = auxBtn = new fltk::Button(315, 15, 115, 80, "Aux");
            o->labelfont(fltk::HELVETICA_BOLD);
            o->labelsize(14);
            o->deactivate();
          }
          o->end();
        }
        o->end();
        fltk::Group::current()->resizable(o);
      }
      
      {
fltk::Group* o = RightGroup = new fltk::Group(455, 5, 340, 590);
        o->set_vertical();
        o->box(fltk::THIN_DOWN_BOX);
        o->begin();
        imageHolder = new fltk::Widget(5, 5, 330, 300, "I should load an image in here");
        
        {
fltk::Group* o = QuestionControlsGroup = new fltk::Group(5, 310, 330, 275);
          o->box(fltk::THIN_UP_BOX);
          o->begin();
          
          {
fltk::Button* o = validateBtn = new fltk::Button(15, 25, 300, 100, "Validate Answer  @+1+");
            o->labeltype(fltk::EMBOSSED_LABEL);
            o->labelsize(16);
            o->callback((fltk::Callback*)cb_validateBtn);
            o->deactivate();
          }
          
          {
fltk::Button* o = nextBtn = new fltk::Button(15, 150, 300, 100, "Next Question  @+1>@+1>[]");
            o->labeltype(fltk::EMBOSSED_LABEL);
            o->labelsize(16);
          }
          o->end();
          fltk::Group::current()->resizable(o);
        }
        o->end();
      }
      o->end();
      fltk::Group::current()->resizable(o);
    }
    o->end();
  }
  win_x = 0; win_y = 0;
  fullscreen_flag = false;
}

void QuestionViewUI::show() {
  mainWindow->show();
}

int QuestionViewUI::selectedRB() {
  for (int i=0; i<4; i++) 
  {
    if ( answerRB[i]->visible() && answerRB[i]->state() )
  	return i;
  }
  return -1;
}
