// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "QuestionViewUI.h"

QuestionViewUI::QuestionViewUI() {
  fltk::Window* w;
   {fltk::Window* o = mainWindow = new fltk::Window(800, 600);
    w = o;
    o->shortcut(0xff1b);
    o->user_data((void*)(this));
    o->begin();
     {fltk::Group* o = new fltk::Group(0, 0, 800, 600);
      o->begin();
       {fltk::Group* o = LeftGroup = new fltk::Group(5, 5, 450, 590);
        o->set_vertical();
        o->box(fltk::THIN_DOWN_BOX);
        o->begin();
         {fltk::Group* o = QuestionView = new fltk::Group(5, 5, 440, 450);
          o->set_vertical();
          o->box(fltk::THIN_UP_BOX);
        }
         {fltk::Group* o = MainControlsView = new fltk::Group(5, 460, 440, 125);
          o->box(fltk::THIN_UP_BOX);
        }
        o->end();
        fltk::Group::current()->resizable(o);
      }
       {fltk::Group* o = RightGroup = new fltk::Group(455, 5, 340, 590);
        o->set_vertical();
        o->box(fltk::THIN_DOWN_BOX);
        o->begin();
        ImageHolder = new fltk::Widget(5, 5, 330, 300, "I should load an image in here");
         {fltk::Group* o = QuestionControlsView = new fltk::Group(5, 310, 330, 275);
          o->box(fltk::THIN_UP_BOX);
          fltk::Group::current()->resizable(o);
        }
        o->end();
      }
      o->end();
      fltk::Group::current()->resizable(o);
    }
    o->end();
  }
}
