// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef QuestionViewUI_h
#define QuestionViewUI_h
#include <fltk/Window.h>
#include <fltk/Group.h>
#include <fltk/Widget.h>

class QuestionViewUI  {
public:
  QuestionViewUI();
  fltk::Window *mainWindow;
      fltk::Group *LeftGroup;
        fltk::Group *QuestionView;
        fltk::Group *MainControlsView;
      fltk::Group *RightGroup;
        fltk::Widget *ImageHolder;
        fltk::Group *QuestionControlsView;
};
#endif
